# frozen_string_literal: true

TOPICS = %w[Technology
            Science
            Movies
            Music
            Health
            Food
            Books
            Visiting-and-Travel
            Business
            Psychology
            History
            Cooking
            Photography
            Sports
            Design
            Fashion-and-Style
            Writing
            Economics
            Mathematics
            Philosophy
            Politics
            Finance
            Marketing
            Television-Series
            Fine-Art
            Literature
            Entertainment
            Journalism
            Healthy-Eating
            Physics
            Current-Events-in-Technology
            Medicine-and-Healthcare
            Science-of-Everyday-Life
            Nutrition
            Education
            Computer-Science
            Current-Events-in-Science
            Songs
            Mobile-Phones
            Technology-Trends
            The-Internet
            Recipes
            Technology-Trends
            Smartphones
            Musicians
            Hollywood
            Novels
            Entrepreneurship
            Psychology-of-Everyday-Life
            India
            Chemistry
            Scientific-Research
            Innovation
            Biology
            YouTube
            Exams-and-Tests].freeze
