default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/boredom_development

test:
  <<: *default
  database: db/boredom_test

production:
  <<: *default
  database: db/boredom_production
